# -*- coding: utf-8 -*-
"""migrate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XxfhaUwStI4S5MfQmDUKrHNMn9ZypFR
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import os

# ---------------------------
# SETUP
# ---------------------------
os.makedirs("outputs", exist_ok=True)

source = pd.read_csv("source_orders_legacy.csv")
target_schema = pd.read_csv("target_orders_schema.csv")
target_cols = target_schema.columns.tolist()

# ---------------------------
# 1. SCHEMA DISCOVERY
# ---------------------------
source_cols = source.columns.tolist()

# ---------------------------
# 2. INTELLIGENT COLUMN MAPPING
# ---------------------------
vectorizer = TfidfVectorizer(analyzer="char", ngram_range=(2, 4))
vectors = vectorizer.fit_transform(source_cols + target_cols)

sim_matrix = cosine_similarity(
    vectors[:len(source_cols)],
    vectors[len(source_cols):]
)

mapping_rows = []

for i, src in enumerate(source_cols):
    j = sim_matrix[i].argmax()
    mapping_rows.append({
        "source_field": src,
        "target_field": target_cols[j],
        "confidence": round(sim_matrix[i][j], 2),
        "mapping_type": "1-to-1",
        "transformation": "rename"
    })

mapping_df = pd.DataFrame(mapping_rows)

# ---------------------------
# 3. MANUAL INTELLIGENCE (1-to-MANY, MANY-to-1)
# ---------------------------
extra_mappings = [
    ("full_name", "first_name", "1-to-many", "string split"),
    ("full_name", "last_name", "1-to-many", "string split"),
    ("full_address", "city", "1-to-many", "string split"),
    ("full_address", "state", "1-to-many", "string split"),
    ("unit_price + quantity", "gross_amount", "many-to-1", "multiplication"),
    ("gross_amount + discount_pct", "discount_amount", "many-to-1", "calculation"),
    ("gross_amount + discount_amount", "net_order_value", "many-to-1", "calculation")
]

for src, tgt, mtype, trans in extra_mappings:
    mapping_df = pd.concat([mapping_df, pd.DataFrame([{
        "source_field": src,
        "target_field": tgt,
        "confidence": 0.95,
        "mapping_type": mtype,
        "transformation": trans
    }])])

mapping_df.to_csv("outputs/mapping_report.csv", index=False)

# ---------------------------
# 4. EXECUTE MIGRATION
# ---------------------------
df = source.copy()

# Rename
rename_map = {
    "customer_id": "customer_key",
    "email": "email_address",
    "phone": "mobile_number",
    "payment_type": "payment_method",
    "order_status": "order_state",
    "order_timestamp": "order_date"
}
df.rename(columns=rename_map, inplace=True)

# One-to-many splits
df["first_name"] = df["full_name"].str.split().str[0]
df["last_name"] = df["full_name"].str.split().str[-1]

df["city"] = df["full_address"].str.split(",").str[-2].str.strip()
df["state"] = df["full_address"].str.split(",").str[-1].str.strip()

# Date transform
df["order_date"] = pd.to_datetime(df["order_date"]).dt.date

# Many-to-one calculations
df["gross_amount"] = df["unit_price"] * df["quantity"]
df["discount_amount"] = df["gross_amount"] * df["discount_pct"] / 100
df["net_order_value"] = df["gross_amount"] - df["discount_amount"]

# Final target dataset
final_cols = [
    "order_id","customer_key","first_name","last_name","email_address",
    "mobile_number","city","state","order_date","product_category",
    "gross_amount","discount_amount","net_order_value",
    "payment_method","order_state"
]

migrated = df[final_cols]
migrated.to_csv("migrated_orders.csv", index=False)

# ---------------------------
# 5. VALIDATION
# ---------------------------
row_match = len(source) == len(migrated)
nulls = migrated.isnull().sum()
duplicates = migrated.duplicated(subset=["order_id"]).sum()

with open("outputs/validation_report.txt", "w") as f:
    f.write("VALIDATION REPORT\n")
    f.write("-----------------\n")
    f.write(f"Row count matched: {row_match}\n\n")
    f.write("Null values:\n")
    f.write(nulls.to_string())
    f.write("\n\n")
    f.write(f"Duplicate order_id rows: {duplicates}\n")

# ---------------------------
# 6. VISUALIZATION DATA
# ---------------------------
mapping_df[["source_field","target_field","mapping_type","confidence"]].to_csv(
    "outputs/mapping_visualization.csv", index=False
)

print("✅ DATA MIGRATION COMPLETED SUCCESSFULLY")

